package Interface;

import Controller.InterfaceController;
import Domain.Resenha;

/**
 *
 * Fontes da imagem:
 * <a href="https://storyset.com/group">Group illustrations by Storyset</a>
 *
 * <a target="_blank" href="https://icons8.com/icon/32Akt39C5Dah/book">Book</a>
 * <a target="_blank" href="https://icons8.com">Icons8</a>
 *
 * <a target="_blank" href="https://icons8.com/icon/vYk5eyYhS0DR/star-of-bethlehem">Star
 * of Bethlehem</a>
 * icon by <a target="_blank" href="https://icons8.com">Icons8</a>
 *
 * <a href="https://www.flaticon.com/free-stickers/education" title="education stickers">Education
 * stickers created by Stickers - Flaticon</a>
 *
 * <a href="https://www.flaticon.com/free-icons/search" title="search icons">Search
 * icons created by Maxim Basinski Premium - Flaticon</a>
 *
 * @author AMANDA FERREIRA MERELIS
 */
public class MainFrame extends javax.swing.JFrame {

    private InterfaceController interfaceController;
    private Resenha resenhaSelecionada = null;

    public MainFrame(InterfaceController interfaceController) {
        initComponents();
        this.interfaceController = interfaceController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        imagem = new javax.swing.JLabel();
        MenuSuperior = new javax.swing.JMenuBar();
        MenuResenhas = new javax.swing.JMenu();
        MenuCadastrarResenha = new javax.swing.JMenuItem();
        MenuListarResenha = new javax.swing.JMenuItem();
        MenuLivros = new javax.swing.JMenu();
        MenuCadastrarLivro = new javax.swing.JMenuItem();
        MenuListarLivro = new javax.swing.JMenuItem();
        MenuAutores = new javax.swing.JMenu();
        MenuCadastrarAutor = new javax.swing.JMenuItem();
        MenuListarAutor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Store MaBook");
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Source Sans Pro", 1, 24)); // NOI18N
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/images/icon-resenha-96.png"))); // NOI18N
        lblTitulo.setText("Bem vindo ao Store MaBook");

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/images/storyset-pagina-principal.png"))); // NOI18N

        MenuResenhas.setText("Resenhas");

        MenuCadastrarResenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/images/icon-resenha-add-16.png"))); // NOI18N
        MenuCadastrarResenha.setText("Cadastrar");
        MenuCadastrarResenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastrarResenhaActionPerformed(evt);
            }
        });
        MenuResenhas.add(MenuCadastrarResenha);

        MenuListarResenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/images/icon-resenha-search-16.png"))); // NOI18N
        MenuListarResenha.setText("Listar");
        MenuListarResenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuListarResenhaActionPerformed(evt);
            }
        });
        MenuResenhas.add(MenuListarResenha);

        MenuSuperior.add(MenuResenhas);

        MenuLivros.setText("Livros");

        MenuCadastrarLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/images/icons-book-add-16.png"))); // NOI18N
        MenuCadastrarLivro.setText("Cadastrar");
        MenuCadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastrarLivroActionPerformed(evt);
            }
        });
        MenuLivros.add(MenuCadastrarLivro);

        MenuListarLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/images/icons-book-search-16.png"))); // NOI18N
        MenuListarLivro.setText("Listar");
        MenuListarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuListarLivroActionPerformed(evt);
            }
        });
        MenuLivros.add(MenuListarLivro);

        MenuSuperior.add(MenuLivros);

        MenuAutores.setText("Autores");

        MenuCadastrarAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/images/icons-typewriter-add-16.png"))); // NOI18N
        MenuCadastrarAutor.setText("Cadastrar");
        MenuCadastrarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastrarAutorActionPerformed(evt);
            }
        });
        MenuAutores.add(MenuCadastrarAutor);

        MenuListarAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceGrafica/images/icons-typewriter-search-16.png"))); // NOI18N
        MenuListarAutor.setText("Listar");
        MenuListarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuListarAutorActionPerformed(evt);
            }
        });
        MenuAutores.add(MenuListarAutor);

        MenuSuperior.add(MenuAutores);

        setJMenuBar(MenuSuperior);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(lblTitulo)
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagem)
                .addGap(199, 199, 199))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrarLivroActionPerformed
        interfaceController.abrirCadastroLivro();
    }//GEN-LAST:event_MenuCadastrarLivroActionPerformed

    private void MenuListarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuListarLivroActionPerformed
        interfaceController.abrirPesquisarLivro();
    }//GEN-LAST:event_MenuListarLivroActionPerformed

    private void MenuListarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuListarAutorActionPerformed
        interfaceController.abrirPesquisarAutor();
    }//GEN-LAST:event_MenuListarAutorActionPerformed

    private void MenuCadastrarResenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrarResenhaActionPerformed
        interfaceController.abrirCadastroResenha();
    }//GEN-LAST:event_MenuCadastrarResenhaActionPerformed

    private void MenuListarResenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuListarResenhaActionPerformed
        interfaceController.abrirPesquisarResenha();
    }//GEN-LAST:event_MenuListarResenhaActionPerformed

    private void MenuCadastrarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrarAutorActionPerformed
        interfaceController.abrirCadastroAutor();
    }//GEN-LAST:event_MenuCadastrarAutorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAutores;
    private javax.swing.JMenuItem MenuCadastrarAutor;
    private javax.swing.JMenuItem MenuCadastrarLivro;
    private javax.swing.JMenuItem MenuCadastrarResenha;
    private javax.swing.JMenuItem MenuListarAutor;
    private javax.swing.JMenuItem MenuListarLivro;
    private javax.swing.JMenuItem MenuListarResenha;
    private javax.swing.JMenu MenuLivros;
    private javax.swing.JMenu MenuResenhas;
    private javax.swing.JMenuBar MenuSuperior;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
